version: '2'
services:
  epaath-runner:
    build:
      context: .  
    restart: always
    environment:
      CI_SERVER_URL: "https://git.olenepal.org/"
      REGISTRATION_TOKEN: "cbcnbyzFufsvowsW6RLM"
      RUNNER_TAG: "development"
      PRIVILIGED_MODE: "true"
    command: "gitlab-runner-auto-register"
    hostname: 'DIND Runner'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
